name: example_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  dio: ^5.8.0+1
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.6
  country_pickers: ^3.0.1
  cupertino_icons: ^1.0.8
  flutter_i18n: ^0.36.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/country/
    - assets/i18n/

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
